package com.nauka;

public enum Command {
    LOGIN_AS_MANAGER,
    LOGIN_AS_CUSTOMER,
    COMPANY_LIST,
    CREATE_COMPANY,
    COMPANY_MENU,
    CAR_LIST,
    CREATE_CAR,
    CREATE_CUSTOMER,
    CUSTOMER_MENU,
    RENT_CAR,
    RETURN_CAR,
    RENTED_CARS,
    BACK_TO_MAIN_MENU,
    BACK_TO_MANAGER_MENU,
    EXIT
}
