package com.nauka.ui;

public enum Command {
    MAIN_MENU,
    MANAGER_MENU,
    MANAGER_COMPANY_LIST_MENU,
    MANAGER_COMPANY_MENU,
    MANAGER_COMPANY_CREATE,
    CUSTOMER_LIST_MENU,
    CUSTOMER_MENU,
    CUSTOMER_CREATE,
    MANAGER_CAR_LIST,
    CAR_LIST_MENU,
    MANAGER_CAR_CREATE,
    CAR_RENT_CHOOSE_COMPANY,
    CAR_RENT,
    CAR_RETURN,
    CAR_RENTED,
    EXIT
}
